name: Build and Push app image

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: npm install

      - name: run tests 
        run: npx mocha test/app.test.js

  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: anestesia01
          password: ${{ secrets.HUB_TOKEN }}

      - name: Build docker image
        run: docker build -t anestesia01/devops-test:v1.0 .

      - name: Push
        run: docker push anestesia01/devops-test:v1.0



